apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config #Name of the config
data: #actual content - key value pairs that hold config info about our mongo-app
  mongo-url: mongo-service #the name of the service for the mongo db application